<acceptance-test-run title="Test user data" name="test_user_data" steps="2" successful="0" failures="1" skipped="1" ignored="0" pending="0" annotated-result="ERROR" result="ERROR" duration="2810" timestamp="2016-02-10T17:36:41.213+02:00">
  <user-story id="com.features.search.DataTest" name="Data test" path="com.features.search"/>
  <tags>
    <tag name="Search" type="capability"/>
    <tag name="Search" type="feature"/>
    <tag name="Search/Data test" type="story"/>
  </tags>
  <test-step result="FAILURE" duration="2564">
    <description>Connect to database</description>
    <error>net.thucydides.core.webdriver.WebdriverAssertionError: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.</error>
    <exception>net.thucydides.core.webdriver.WebdriverAssertionError:com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.&#xd;
[com.mysql.jdbc.Util.handleNewInstance(Util.java:404), com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981), com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:339), com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253), com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286), com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085), com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:795), com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:44), com.mysql.jdbc.Util.handleNewInstance(Util.java:404), com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400), com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327), com.helpers.JDBCHelper.connectToDB(JDBCHelper.java:16), com.steps.serenity.DBSteps.connect_to_database(DBSteps.java:19), com.features.search.DataTest.test_user_data(DataTest.java:26), org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86), org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38), org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459), org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675), org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382), org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)]</exception>
  </test-step>
  <test-step result="SKIPPED" duration="2">
    <description>Create user: &lt;span class=&apos;step-parameter&apos;&gt;testUser, testPassword, test@mail.com&lt;/span&gt;</description>
  </test-step>
</acceptance-test-run>